### ISSUE TITLE
(config) true/false LED use

### ISSUE THREAD

**Issue by framboise-pi** [framboise-pi/MMM-MySenseHat#14]
- true/false for using 8x8 LED

modes
- pixelart/animations true/false
- weather true/false
- gmail new mail true/false
- MMM-MySenseHatTamagotchi
- random between choosen modes true/false

**Comment by lavolp3** [comment]
you could include a mode for the 8x8 led matrix in the config options,  like `mode: weather` or `mode: mail`.
Or you could combine modes and in a certain interval show one of the mode options.
E.g. modes weather and mail. In a certain interval change to the other mode and show the respective label for the mode.
